server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${DB_HOST}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: 5000
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    tags-sorter:  alpha
    operations-sorter: method
    enabled: true
  paths-to-match:
    - /**

management:
  # Info 정보 사용 설정
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    # Git 정보 사용 설정
    git:
      mode: full
  endpoint:
    shutdown:
      enabled: true
    # Health 정보 사용 설정
    health:
      show-details: always
  #      show-components: always # 간소화 노출
  endpoints:
    web:
      exposure:
        include: '*'

e:
  auth:
    google_client_id: ${GOOGLE_CLIENT_ID}
    google_client_secret: ${GOOGLE_CLIENT_SECRET}
    redirect_url: http://localhost:3000/api/auth/google
    github_client_id: ${GITHUB_CLIENT_ID}
    github_client_secret: ${GITHUB_CLIENT_SECRET}
  payapp:
    user_phone: ${PAY_USER_PHONE}