spring:
  datasource:
    url: ${DB_HOST}/devmate?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter:  alpha
    operations-sorter: method
  paths-to-match:
    - /api/**